### ISSUE TITLE
Instructions at lubuntu.me/tip-compose-key/ don't work

### ISSUE THREAD

**Issue by lee-tts** [lubuntu-team/lubuntu.me#1]
Hi, 

The tip shown at the address below does not seem to work on Lubuntu 18.04.

My current setup:

    Distributor ID:	Ubuntu
    Description:	Ubuntu 18.04.1 LTS
    Release:	18.04
    Codename:	bionic

![image](https://user-images.githubusercontent.com/39074607/45526352-58de9a00-b809-11e8-8c22-308db5d6738c.png)

Setting a value for compose:__ will make the assigned key stop doing its original action, but not act as a Compose key.

I'll submit a PR if someone can tell me the current 'right way' to get the compose key working. 

Thanks!

Lee

**Comment by wxl** [comment]
That most certainly is the right way. You need to select one of the options in `grep compose /usr/share/X11/xkb/rules/base.lst`. Assuming you've done that (`compose:caps` is one such solution), then you'll need to make sure you hit the little save button. Then it just works. I just tested this on 18.04 myself and can confirm it works (with caps).

**Comment by lee-tts** [comment]
Thanks for your input!

There must be something else wrong with my setup then, because it's not working for me.

`setxkbmap -query` gives:

    rules:      evdev
    model:      pc105
    layout:     us
    variant:    ,
    options:    ,compose:caps

xev

    KeyPress event, serial 48, synthetic NO, window 0x3400001,
    root 0x1ae, subw 0x0, time 817555, (-484,508), root:(387,539),
    state 0x0, keycode 66 (keysym 0xff20, Multi_key), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: True

xmodmap -pm

    xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):
    
    shift       Shift_L (0x32),  Shift_R (0x3e)
    lock      
    control     Control_L (0x25),  Control_R (0x69)
    mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
    mod2        Num_Lock (0x4d)
    mod3      
    mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
    mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
    


It looks like the option saved properly but it still doesn't give me compose ability, whether in Chrome, terminal, leafpad ...

It's like something is overriding it somewhere.

**Comment by wxl** [comment]
Sorry for the delay. Busy trying to get 18.10 out the door. Anyways, can't reproduce, and I've got the exact same results as you. Maybe getting a little more verbose might help:

```
$ setxkbmap -print -verbose 10                                                                             
Setting verbose level to 10                                                                                          
locale is C                                                                                                          
Trying to load rules file ./rules/evdev...                                                                           
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.                                                                                                             
Applied rules from evdev:                                                                                            
rules:      evdev
model:      pc105
layout:     us
variant:    ,
options:    grp:shift_caps_toggle,compose:caps
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+inet(evdev)+group(shift_caps_toggle)+compose(caps)
geometry:   pc(pc105)
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+us+inet(evdev)+group(shift_caps_toggle)+compose(caps)"      };
        xkb_geometry  { include "pc(pc105)"     };
};
```

**Comment by lee-tts** [comment]
Not to worry! I appreciate you taking time for this. 

Output looks the same for me, except for the grp which I assume is for switching layouts.

The grp thing led me think to add the English US layout in ibus (previously I was using one other non English layout, and typing English in ibus's ASCII mode). Compose key now works. 

Looks like it's not your problem anymore!
